# Autor: Robson Vaamonde
# Site: www.procedimentosemti.com.br
# Facebook: facebook.com/ProcedimentosEmTI
# Facebook: facebook.com/BoraParaPratica
# YouTube: youtube.com/BoraParaPratica
# Linkedin: https://www.linkedin.com/in/robson-vaamonde-0b029028/
# Instagram: https://www.instagram.com/procedimentoem/?hl=pt-br
# Data de criação: 12/09/2026
# Data de atualização: 17/09/2026
# Versão: 0.02
# Testado e homologado para a versão do Ubuntu Server 26.04.x LTS 64x
# Testado e homologado para a versão do Node Exporter 1.12.x
#
# ======= BLOCO DE CONFIGURAÇÃO BÁSICA DO NODE EXPORTER NO LINUX ======= 
#
# Bloco de configuração das opções do Node Exporter no Ubuntu Server
OPTIONS="\
  --web.disable-exporter-metrics \
  --collector.systemd \
  --collector.systemd.unit-include=^(sshd|chrony|mdmonitor|lvm2-monitor|unattended-upgrades|netplan-configure|systemd-resolved|systemd-timedated)\.service$ \
  --collector.timex \
  --web.listen-address=:9100 \
"